print('Welcome and thanks for playing legaly distinct Mad Libs!\n Please follow the prompts bellow!')
print(' ')
adjective_one=input('Please Type an Adjective: ').lower ('')
proper_noun_one=input('Please Type a Proper Noun: ').capitalize ('')
verb_one=input ('Please type a verb: ').lower ('')
adjective_two=input('Please Type an Adjective: ').lower ('')
adjective_three=input('Please Type an Adjective: ').lower ('')
number=input('Choose a number: ').lower ('')
adjective_four=input('Please Type an Adjective: ').lower ('')
print(' ')
print(' Your Story is....')
print(f'Harold the Cat was a very {adjective_one} cat. {proper_noun_one} did not like Harold very much since he {verb_one} without him. ' )
print(f'Because of this dislike {proper_noun_one} was going to play a {adjective_two} prank on him. ' )
print(f'While {proper_noun_one} was planning his prank, he neglected to keep up with his {adjective_three} income, so he was visited by')
print(f'{number} {adjective_four} members of the interal revenue service and was disposed. {adjective_one} Harold allways paid his taxes. ')