print ( )
print ( )
print('Please answer the questions truthfully ')
print ( )
first_name=input('What is your first name? ').capitalize()
last_name=input('What is your last name? ').upper()
job_title=input('What is your Job? ').title()
id_number=input('What is your Id Number? ')
email_address=input ('Input your email here ').lower()
phone_number=input ('Input your phone number here ')
training=input('Have you compleated the training?')
current_location=input('Where are you right now? ')
home_address=input('What is your Home Address? ').title()
vacation_time_frame=input('When are you going to be on vacation? ').upper()
print('')
print('The ID Card Is:\n---------------------------------------')
print(f'{last_name},{first_name}')
print(f'{job_title}')
print(f'ID:{id_number}')
print('')
print(f'{email_address}') 
print(f'{phone_number}')
print('----------------------------------------')
print( ) 
print( )
print(f'We defenatly wont be vistiing your house at {home_address} on {vacation_time_frame},') 
print(f'Please do not move from {current_location} for the next hour or so.')
print( )
print( )
print( )